theme: jekyll-theme-architect
# remote_theme: pages-themes/slate@latest
# plugins:
#   - jekyll-remote-theme
title: "📦  @nberlette/emoji"
description: "Straightforward emoji library"
show_downloads: true
github:
  zip_url: "https://github.com/nberlette/emoji/archive/refs/tags/v2.0.0-next.1.zip"
  tar_url: "https://github.com/nberlette/emoji/archive/refs/tags/v2.0.0-next.1.tar.gz"
  owner_url: "https://n.berlette.com"
  repository_url: "https://github.com/nberlette/emoji.git"
